### ISSUE TITLE
Add Machine Word size in autoconfigure and expose the macro

### ISSUE THREAD

**Issue by satvikc** [raaz-crypto/raaz#115]
I need similar stuff as done [here](https://github.com/ghc/ghc/blob/master/includes/MachDeps.h)

I need the macro "WORD_SIZE_IN_BITS" exposed. Is it possible to use this header file directly? Otherwise we might need to have this flag exported in the auto-configure.

timesWord2# is available in GHC 7.6 so we might as well use that.

**Comment by piyush-kurur** [comment]
can you close this ticket if it is taken care of?

**Comment by piyush-kurur** [comment]
Looks like this ticket is no more relevant. Closing it.
