### ISSUE TITLE
New travis build script

### ISSUE THREAD

**Issue by abhijaju** [raaz-crypto/raaz#165]
I have written a script for building packages programmatically to resolve dependencies. It's  at the `script/travis-build.hs` of `x-travis` branch in my repository. I have followed the following steps to build a package:
* `cabal install --only-dependencies`
* `cabal configure --enable tests`
* `cabal build`
* `cabal test --show-details='failures'`
* `cabal install`

The execution stops if any of the steps in any of the packages fails with appropriate exit-code.

**Comment by piyush-kurur** [comment]
This has been merged. However I am not closing it as

1. There is still some stale code in the scripts directory
2. I do not think the process has been documented properly

**Comment by piyush-kurur** [comment]
No more relevant after the get package merge #207
