### ISSUE TITLE
re-organising all primitives into one haskell package.

### ISSUE THREAD

**Issue by piyush-kurur** [raaz-crypto/raaz#207]
Currently we have a single raaz-core package that contains all the
generic stuff and hashes separately in raaz-hash, ciphers in
raaz-cipher etc. While this gives greater granularity to the package
structure, it also leads to some ugliness.

I am proposing the following radical change to the organisation. Since
this organisation is radical I want to take a decision only after
widespread discussion.

The main idea is to have a single package that contains all the
cryptographic primitives. Individual protocols can then be in separate
packages.

Why this change ?
1. If at all an independent package would use the raaz libraries it
   would be for the primitives. I do not see a reason of some package
   (third party) that depends on raaz-core but not say raaz-hash or
   raaz-cipher. While it is also true that there can be packages that
   need the hashes (version controllers come in my mind) but not the
   ciphers or public key infrastructure, I think this is rather a high
   handedness that we can take.
2. The package will have lesser dependency on QuickCheck, HUnit and
   test-framework-*. They will be required only for developers and not
   end-users.
3. One can use a trivial travis build script.
4. Possibility of releasing the primitives independent of the
   protocols.
# New orgainisation.
1. A single package that contains all the cryptographic
   primitives. Some possibilities of this package.
   - raaz-core       (my prefered version)
   - raaz-primitives
   - or just raaz.
2. If we do want to reflect some of the old hierarchical structure we can have some structure
   like the following. If need be we can also provide flags to disable parts of the structure.
   - core/    - All the stuff in the current core package will go here
   - core/tests - the tests of the core package
   - core/docs  - the documentation regarding core stuff.
   - hashes/  - All the hashes.
   - hashes/tests
   - ...
   - system/  - system specific compilation units etc.
   - system/posix   - For posix systesm
   - system/windows - For windows system etc

**Comment by satvikc** [comment]
This sounds like a nice idea. Flags to disable parts like hashes, ciphers etc. can be implemented later if requested.

**Comment by piyush-kurur** [comment]
I am going for this re-organisation. Coming to think of it there is very little reason to even have separate compilation of primitives. I guess there for a simpler design is fine.

**Comment by piyush-kurur** [comment]
The status of this is that we now have the hashes and aes crypto merged. Other issues are pending.

**Comment by piyush-kurur** [comment]
We now have chacha20 cipher in the mix.

**Comment by piyush-kurur** [comment]
With the new design, we have gone much ahead of this point. As such this ticket is now no more
relevant.
