### ISSUE TITLE
Daily Builds of Raaz on Launchpad

### ISSUE THREAD

**Issue by abhijaju** [raaz-crypto/raaz#210]
We would require regular builds of Raaz against several Ubuntu versions which can be done using Launchpad by creating a PPA and importing code from the git repository which is then packaged by a `source package recipe`.

**Comment by piyush-kurur** [comment]
I would like to make a decision on #207 before this is attempted. If
we make the changes according to decision #207 things can get a lot
simpler in building. As you can see I am for #207, so is @satvikc

**Comment by piyush-kurur** [comment]
Now that there is a debian thanks to  build I think it is safe to close this issue. We should remove the raaz repositories in launchpad so that there is no confusion. What is your opinion @spwhitton?

**Comment by spwhitton** [comment]
No opinion!  I don't personally use Launchpad.

Note that Debian's build frequency is far from "daily".

-- 
Sean Whitton

**Comment by piyush-kurur** [comment]
I think it is fair to close this ticket as we have not been able to do much about it. In any case, thanks to @spwhitton raaz has entered the debian world with builds across multiple architectures. Therefore I do not see much utility to this
