### ISSUE TITLE
Daily Builds of Raaz on Open Build Service (OBS)

### ISSUE THREAD

**Issue by abhijaju** [raaz-crypto/raaz#211]
This is required because we need to build and test Raaz against several linux distros and several different architecture. Raaz uses various packages such as `integer-gmp` which are not available in many of the current linux distros, but is planned to get included in their newer versions. So, we can start  building and testing Raaz against various architectures afterwards.

**Comment by piyush-kurur** [comment]
Same goes here. I would prefer if we can quickly decide on #207.

**Comment by piyush-kurur** [comment]
I am closing this as I do not think we have resources to do this at the moment. Will visit later
