### ISSUE TITLE
Can using vector library help.

### ISSUE THREAD

**Issue by piyush-kurur** [raaz-crypto/raaz#214]
It seems that almost all our datastructures involve arrays of
word32/64 or what ever. Why not use vectors for it. Like for example
Sha1 will look like

```haskell

data Sha1 = Sha1 (Vector Word32BE)

```

This way we will need to write for generic vector the following class
and use it for individual ones.

1. Storable/Endian store instances for generic Vectors
2. Timing safe equality for vectors using folds ect.

**Comment by piyush-kurur** [comment]
Of course, one cannot have storable/endian store instances for vectors
directly as their sizes vary. But when used in the context of a
particular type like sha1 we know the vector is of size 5.

We might even want the vectors to be Data.Vector.Storable instances in
which case we can often pass the data directly to C functions.

**Comment by piyush-kurur** [comment]
With merge 5720cfd we can think of attacking this problem. All the
necessary machinary is there to cleanup the definitions of the types
in question.

**Comment by piyush-kurur** [comment]
We need to now fix the data types like SHA1 etc to use vectors. Please
send in the pull requests for this on to the brance use-vector

**Comment by satvikc** [comment]
Did it change benchmarks at all?

**Comment by piyush-kurur** [comment]
On Fri, Apr 17, 2015 at 10:01:35AM -0700, satvikc wrote:
> Did it change benchmarks at all?
> On Apr 17, 2015 6:30 AM, "Piyush P Kurur" <notifications@github.com> wrote:
> 
> > Closed #214 <https://github.com/raaz-crypto/raaz/issues/214> via 17720b5
> > <https://github.com/raaz-crypto/raaz/commit/17720b585f16c3d24ee7ff0859be90b1603892a5>

Where exactly is the bench marks. I donot have it. It think it is in
you MTP somewhere.  I do not expect it to change much but for the
reference implementation being slightly slower.

Can the benchmarks be put some where in the repo? Please wait for the
grand reorganisation that we are planning. I have some memory code that is
still to get into the main repo.

**Comment by piyush-kurur** [comment]
See also #219 for some improvements that we can do on reference implementation
