### ISSUE TITLE
Liquid Haskell

### ISSUE THREAD

**Issue by piyush-kurur** [raaz-crypto/raaz#227]
It would be interesting to incorporate stronger guarantees into raaz by using Liquid Haskell. Document in responses to this ticket places where liquid haskell can give non-trivial gurantees.

**Comment by alanz** [comment]
You do not say what your library is.  Please add a link to the source.

**Comment by piyush-kurur** [comment]
@alanz. I thought it was obvious from the fact that this is the issue tracker for the raaz package and this is the issue tracker for it.

**Comment by piyush-kurur** [comment]
I just updated the comment so that the ambiguity is gone.

**Comment by alanz** [comment]
Sorry, I thought this was the liquid haskell issue tracker.

**Comment by ranjitjhala** [comment]
Hi @piyush-kurur --  this is interesting! are there particular places inside the `raaz` that you had in mind as starting points for investigations?

**Comment by piyush-kurur** [comment]
On Mon, Apr 03, 2017 at 08:26:11PM -0700, Ranjit Jhala wrote:
> Hi @piyush-kurur -- this is interesting! are there particular places
> inside the `raaz` that you had in mind as starting points for
> investigations?

Thanks for your interest. I have been too lazy about documenting this
but now that you have asked, let me put in some stuff that directly
comes to my mind.

1. The function `unsafeFromList` in `Raaz.Core.Types.Tuples`. This
   should be the easiest however, the function is not used in the
   module where it is defined but at other locations where tuples are
   constructed `Raaz.Hash.Sha1.Internal`.

2. The monoid action laws for pointers in `Raaz.Core.Types.Pointer`. This takes
   care of most pointer arithmetic constructions.

3. Some laws regarding pointer alignment `R.C.T.Pointers`

4. Most high level combination of pointer manipulation code is taken
   care of by the Semi-Direct product construction. But there are some
   "base" cases that have to be done "by hand". The modules R.C.Write
   and R.C.Applicative.Parse and R.C.Memory has some of these. I am
   not sure what kind of properties might make these "by hand"
   constructions more robust but it would be interesting to explore this module

**Comment by piyush-kurur** [comment]
As an experiment I have started a branch https://github.com/piyush-kurur/raaz/tree/liquid-haskell. Just enabled liquidhaskell-cabal but unfortunately does not work easily on my machine.

- For cabal-install  the recommended version seems to be > 1.24 which I do not have currently (debian testing here)
- For stack they require lts-5.5 but for some strange reason stack < 7 does not work for me (linker error)

So I have not tested it. Just enabled it. Will be playing around with it when the stars align perfectly. As of now I plan to keep a separate branch for the modifications to `Setup` and `.cabal`. I will do the testing locally.

I hope this sounds good for experimentation.

**Comment by alanz** [comment]
Liquid Haskell requires the ghc 7.10.3 compiler. 

You may have to do `stack setup` if it is not already on your system. 

And if it is on your system but is not the no-pie version then you will get linker errors, in which case you will have to reinstall it.

**Comment by piyush-kurur** [comment]
@alanz I managed to compile the latest github head on my machine. Let me see how it goes this time.

**Comment by ranjitjhala** [comment]
Fingers crossed! Do let us know if you run into issues.

**Comment by piyush-kurur** [comment]
Yaahoo now liquidhaskell is successfully integrated. Travis integration is in TODO (linux image does not have z3 or as far as I can see the other solvers). Trying it with travis:osx image now.

Now comes the hard part of writing the actual specs and fixing the type check failures that liquidhaskell reports.

**Comment by piyush-kurur** [comment]
@ranjitjhala Unfortunately it looks like travis does not have any of the sat solvers required by liquid haskell. So travis buid has to stay. But otherwise every thing looks fine

**Comment by piyush-kurur** [comment]
Now Liquid haskell verifies all the code in the Raaz/Core/Encode (base16 and base64) encoding modules. I would like to put some more refined types to some of these functions but my current knowledge of liquid haskell is not sufficient to hack it. Please see the TODOs in the file Raaz/Core/Encode/Base16 and Raaz/Core/Encode/Base64.hs
