### ISSUE TITLE
Building on ARM 

### ISSUE THREAD

**Issue by piyush-kurur** [raaz-crypto/raaz#259]
It is more than necessary to have regular builds on ARM. Particularly in view of #256.

**Comment by piyush-kurur** [comment]
A solution would be to build it in Ubuntu Launch Pad

**Comment by sakshamsharma** [comment]
I see this:
https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html

One possible issue would be that this involves an extra time dependency for building. And caching *inside* the QEMU VM might be a bit too much to expect from Travis. Travis has a 50 minute hard deadline, and this guy says setting up the VM takes 10 out of that. So there would be 40 mins left for the x64 as well as ARM tests.

I guess we won't know until it is tested.

**Comment by piyush-kurur** [comment]
I was thinking more of using something like Ubuntu Launch Pad. Last time I checked, it allowed building for different architecture. @abhijaju had also tried the OpenSUSE build system. The OpenSUSE build system allows testing across OS'es and architectures. For example, if we create a .deb package for raaz then we can test it in a virtual Debian container provided by OpenSUSE. The build is slightly different from travis because the container does not allow internet access. The dependencies are met using the debian packages that are available there.

This is the (slightly outdated) wiki where we have said something on this.

https://github.com/raaz-crypto/raaz/wiki/Continuous-build-system

**Comment by piyush-kurur** [comment]
By the way I do not mind the ARM on travis if you are willing to give it a shot. Just wait for some changes that I am about include.

**Comment by piyush-kurur** [comment]
@abhijaju  You have created a raaz project on launchpad. Can you transfer the ownership to me?

Currently there is a repository (bzr) in it. I saw  that launchpad now supports git. I would like to put a mirror of raaz on launchpad.

**Comment by abhijaju** [comment]
@piyush-kurur I've transferred ownership to **raaz-crypto** team on launchpad

**Comment by abhijaju** [comment]
Let me know if you need ownership of OpenSuse Build Service account

**Comment by piyush-kurur** [comment]
@abhijaju thanks. Not right now. May be latter.

**Comment by piyush-kurur** [comment]
Launch pad is really confusing. I managed to push the latest git repository on to raaz but some how your (@abhijaju) seems to appear in the Development focus section. I can see the master branch if I click some sequence of links but I have no idea how this works.

**Comment by piyush-kurur** [comment]
Since raaz  now has a debian package and the debian builds across multiple architectures, this issue is no more relevant.
