### ISSUE TITLE
reading data from a Handle to locked memory

### ISSUE THREAD

**Issue by joeyh-purism** [raaz-crypto/raaz#263]
Raaz needs a primitive such as:

readHandle :: Handle -> MT mem ByteString

As far as I can see, this does not exist, so the only way to read data from the outside world is using regular IO functions, and those don't immediately read the data into a locked memory buffer.

My use case involves reading a gpg secret key from a pipe, and AES encrypting it. The key data should remain in locked memory at all times.

**Comment by piyush-kurur** [comment]
`ByteString` do not have a bound on their size. For the memory interface to work you need fix the size of your memory element.

There are two posibilites.

1. If you know the size of the key, you can define a memory element of the appropriate size and then fill it from the pipe. 

2. You can incrementally process the input. Allocate a secure memory buffer (a new type of fixed length) and then keep filling it with hGetBuf and encrypting stuff. Make sure that the handle's buffering mode is set to `NoBuffering`

**Comment by joeyh-purism** [comment]
So I gather it's already possible to do this, using hGetBuf with a
Ptr from the Memory's underlyingPtr.

If so, feel free to close..

-- 
see shy jo

**Comment by piyush-kurur** [comment]
Yes. You can do that. I think for your application you can use the function `withPointer :: Memory mem => (Pointer -> IO b) -> MT mem b`. Besides `MT mem` is an instance of `MonadIO`. So if you want to do some IO in between you can just do a `liftIO`

**Comment by piyush-kurur** [comment]
@joeyh-purism: You might be interested in the additional changes (adf5af3) that I have done in the memory element. It now supports direct transfer of data between buffers to memory element.
