### ISSUE TITLE
Benchmarking primitives

### ISSUE THREAD

**Issue by piyush-kurur** [raaz-crypto/raaz#264]
To make sure the implementations provided here are sane we need to
benchmark it for performance. The benchmarking should be as follows
1. Benchmark against other libraries (cryptonite, HOpenSSL).
2. Benchmark different implementations within raaz.

When benchmarking against cryptonite/HOpenSSL make sure to benchmark
against the following input
1. Raw byte buffers
2. Strict ByteString
3. Lazy ByteString.

**Comment by piyush-kurur** [comment]
@satvikc . Do you have the old benchmarks that were part of your M.Tech thesis. Although the interface has changed dramatically. It might make sense to have a look at it.

**Comment by satvikc** [comment]
Let me check on my fork. If I don't have it there then I might not have it
as hard-disk of my old laptop died.

**Comment by piyush-kurur** [comment]
Benchmark of implementations within raaz will be maintained here. Benchmarks across libraries should
be in a separate repo.

**Comment by piyush-kurur** [comment]
I am closing this as there is a primitives benchmark for some time.
