### ISSUE TITLE
Debian build fails

### ISSUE THREAD

**Issue by piyush-kurur** [raaz-crypto/raaz#278]
raaz fails on Debian hurd and kFreeBSD. The reasons are obvious.

1. The macro to test whether /dev/urandom exists is not testing for hurd

2. Debian kFreeBSD is being detected as freebsd and hence we are attempting the endian conversion
    functions of freebsd where as the actual userland is gnu.

**Comment by piyush-kurur** [comment]
Here is the link to the build

https://buildd.debian.org/status/package.php?p=haskell-raaz&suite=sid

**Comment by piyush-kurur** [comment]
@spwhitton I believe that I have closed the debian build problem on hurd and kFreeBSD. Is it possible to try out the build from the github head. Note that I have not made a new release yet and am waiting for the blake2 code to get into the repository before making the new release.

**Comment by piyush-kurur** [comment]
@spwitton not to mention but feel free to reopen this ticket if all is not well.

**Comment by spwhitton** [comment]
Unfortunately, no, we can't trigger a build without uploading a new
version to Debian and we prefer to upload only released versions.

-- 
Sean Whitton

**Comment by piyush-kurur** [comment]
@spwitton I just released a new version of raaz-0.1.0.

**Comment by spwhitton** [comment]
On Mon, Feb 27, 2017 at 03:17:14AM -0800, Piyush P Kurur wrote:
> @spwitton I just released a new version of raaz-0.1.0.

Thanks.  Debian is currently frozen, pending the release of our new
stable version.  So I can't upload at present.

-- 
Sean Whitton

**Comment by spwhitton** [comment]
Sorry, I did not think through my last reply.  I can upload the new version of raaz to our experimental repository, which will not affect keysafe, but will permit you to view build logs.  I'll let you know when I've done that.  Thank you for your work on this issue.

**Comment by spwhitton** [comment]
https://buildd.debian.org/status/package.php?p=haskell-raaz&suite=experimental
