### ISSUE TITLE
System random for windows

### ISSUE THREAD

**Issue by piyush-kurur** [raaz-crypto/raaz#280]
Support system prg for windows platform.

**Comment by piyush-kurur** [comment]
This should be a straight forward ffi for the system prg call on windows

**Comment by hvr** [comment]
My go-to package for industrial-strength entropy-gathering is http://hackage.haskell.org/package/entropy

Does that package suit your needs?

**Comment by piyush-kurur** [comment]
On Mon, Jun 19, 2017 at 05:52:09AM -0700, Herbert Valerio Riedel wrote:
> My go-to package for industrial-strength entropy-gathering is http://hackage.haskell.org/package/entropy

This package uses /dev/urandom on all POSIX systems which raaz already
does. Besides many of the specific unixes (e.g Open/Net-BSDs) have
their own recommended entropy source (arc4random). Linux has its own
system call getrandom. The advantages of these calls over just reading
from /dev/urandom are

1. They block on situations when the system entropy is low (e.g startup)

2. They handle all kinds of exceptions.

3. One is spared of using an extra file descriptor

4. Works even in containers where /dev/urandom might not even exist.

As far as I see the entropy package does not do this. Raaz on the other hand
has (untested) integration of arc4random on bsd and getrandom on linux.

**Comment by piyush-kurur** [comment]
There is one thing that I forgot to mention. In addition I want an interface that reads stuff directly into a pointer. The current CPRG include in raaz can keep its internals in a locked memory. This is an added security when one is generating long time keys such as keys of PKI.

The entropy package only allows reading as a bytestring which is in the haskell heap and thus is not in
locked memory.

**Comment by Mistuke** [comment]
I think [CryptGenRandom](https://msdn.microsoft.com/en-us/library/aa379942.aspx) meets your needs. 
If it does I can provide you with the appropriate bindings.

**Comment by piyush-kurur** [comment]
@Mistuke That would be great. Let me also try enabling [Appveyor](https://www.appveyor.com/) so that we have CI on windows

**Comment by piyush-kurur** [comment]
Just one point. In the document [CryptGenRandom](https://msdn.microsoft.com/en-us/library/aa379942.aspx), it gives the C++ interface. There might be some complication due to function
name mangling that C++ compilers do. If there is a C interface that would be better.

**Comment by Mistuke** [comment]
That's a quirk of that documentation page (someone probably mislabeled it). The interface is C, the Win32 apis are always C :)
