### ISSUE TITLE
Memory locking for windows

### ISSUE THREAD

**Issue by piyush-kurur** [raaz-crypto/raaz#281]
Support memory locking for windows

**Comment by piyush-kurur** [comment]
It should be a straight forward fix as all one needs is a ffi interface to the appropriate version of mlock and munlock

**Comment by Mistuke** [comment]
The proper calls should be [VirtualLock](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366895(v=vs.85).aspx) and [VirtualUnlock](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366910(v=vs.85).aspx).

If no one else does I can provide the appropriate bindings for you.

**Comment by piyush-kurur** [comment]
@mistuke It would be great if you can do that. Thanks a lot in advance.

**Comment by piyush-kurur** [comment]
@mistuke I have added an appveyor.yml and it is indeed building but there is an error saying that raaz/core/endian.h is missing. This might be due to the difference in the path separator. Is it possible for you to check this as well?

**Comment by Mistuke** [comment]
@piyush-kurur yup, I can take a look tonight. The path separator isn't an issue as windows accepts boths front and back slashes. quick glance don't you miss `cbits` here too https://github.com/raaz-crypto/raaz/blob/master/raaz.cabal#L182

**Comment by piyush-kurur** [comment]
@mistuke I think you are correct. I am surprised why it did not throw up an error on posix?

**Comment by piyush-kurur** [comment]
I updated the install-include stuff. But looks like that is not the problem. The build still fails.
<https://ci.appveyor.com/project/raaz-crypto/raaz>. Coming to think of it the install-include need not have anything.

What happens if the FFI code uses include `<raaz/crypto/endian.h>`. As this is compiled by the C compiler, I am not sure how it will deal with the change in path separator.

**Comment by piyush-kurur** [comment]
I have now included a -v3 in the appveyor build. So you should be able to see the errors it is throwing up.

**Comment by Mistuke** [comment]
Actually, the error isn't referring to `endian.h` in `raaz/crypto` it's referring to the system header `endian.h` which Windows does not have.

I've started and am almost done with the Entropy implementation (which ended up being slightly more involved than I thought). But I'll finish it in the weekend and send a pull request as I also have to figure out how to use `Raaz.Core.Types.Pointer`.

**Comment by piyush-kurur** [comment]
Okey I believe I have fixed the endian issue with the commit 092a815. Now the error it is showing is the non-existant `Raaz/Entropy.hs` which of course is expected. Let me know if there is some other issue.

**Comment by Mistuke** [comment]
Ah, thanks! I should be able to finish the Entropy code tonight, the locking code should be simpler.
