### ISSUE TITLE
Dynamic choice of implementation.

### ISSUE THREAD

**Issue by piyush-kurur** [raaz-crypto/raaz#300]
The current code base has facility to build multiple implementations. The Recommendation instance for each primitive chooses the default implementation. With some change this could be made dynamic by probing for cpu-features at runtime an selecting primitive appropriately.

More thought would be needed on this.

**Comment by piyush-kurur** [comment]
@vincenthz can you comment how cryptonite does this?

**Comment by piyush-kurur** [comment]
Just realised that this has a subtle problem unless we are very careful. Implementations that use for example avx2 needs to be compiled with -mavx2. But if we provide this as a global option all code would be compiled with this option. So blindly putting stuff in the cabal file will not work. The C library will need to be compiled and packaged separately for this to work.

**Comment by TomMD** [comment]
N.B. you can use a `custom` build script to test if the compilation chain supports a particular flag, such as `-mavx2` (see https://github.com/TomMD/cipher-aes128/blob/master/Setup.hs).

Cryptonite's predecessor, aes-cipher borrowed and improved on a design from aes-cipher128 to check the `cpuid` and set a jump table to point to optimized routines if AESNI exists (or remain the pure C routines). A similar thing can be done here.

**Comment by piyush-kurur** [comment]
Thanks @TomMD for your suggestion. If I understand things correctly 
(1) The setup script checks whether avx2 (or for that matter some other internsics) are available at build time where as
(2) The brach_table does it at run time 

In raaz there is the class Recommended (https://github.com/raaz-crypto/raaz/blob/master/Raaz/Core/Primitives.hs#L66) 
I was thinking of updating that to do a run time selection of the implementation

**Comment by piyush-kurur** [comment]
There is one difficulty though. Let us say we have chacha20_avx2 which is the implemetation that uses avx2, I need to compile it with the flags mavx2. What would happen if gcc optimises some other implementation chacha20_portable to use avx2 instruction?

The only solution I see is that one needs to completely built the cbits with each of the implementations in different files compiled with different option i.e. 

```
gcc -c -mavx2 chacha20-avx2.c
gcc -c chacha20.c 
```
and package it as a  a library and ffi haskell to it.

**Comment by TomMD** [comment]
Ah yes, interesting.  Is it not the case that gcc will use `aesni` instructions without explicit use of intrinsics even when `-maes` is passed.  AVX{,2} is different though as gcc will use AVX instructions as desired so you will need to perform two separate compilations of the C files probably using the `make` build-type (instead of `custom`) in Cabal, which is a lot more work.

It might be in your best interest to avoid all these options and just use a compile-time cabal flag to enable AVX2 (or disable it) universally until/unless Cabal adds a per-file compilation flag option accessible by the `Custom` build type.  I'm tempted to make a Cabal issue for exactly that.

N.B. A cabal flag, instead of complex Setup.hs, is exactly what Vincent has done in the past so it's a decision with precedent if that eases your mind.  Everyone appreciates when the build just automatically does the right thing but it just isn't always an option.

**Comment by piyush-kurur** [comment]
@hvr is such a feature (i.e. per file gcc flags) being planned in cabal. If not, do you think it makes sense to raise this as an issue.

**Comment by piyush-kurur** [comment]
@TomMD Currently I am using cabal flags. But it is ugly. The cabal file being a simple file makes life a bit difficult whe you have a lot of such conflicting options. In any case I have raised an issue in haskell/cabal repo 
let us see what they have to say.

**Comment by piyush-kurur** [comment]
CPU probe with a jump instruction might not always work due to the inherent ambiguity of performance figures. When per file flags are available, the following might be a better strategy for raaz (this is not as good as cpuprobe but acceptable).

1. Write different implementations and c and compile it with the most optimistic flags. For example, we can   have (portable-c with (1) Plain O2, (2) O2 + vectorise (3) O2 + vectorise + avx2 (4) Other hand optimised versions.
    
2. Expose a cputune executable from the package that spits a implementation selection file by running a bencmarks. We have this selected globally as the library data.

This way the packager can build the packages and the user, after installing the package can tune it for her machine.

**Comment by piyush-kurur** [comment]
Gcc (at least some versions) supports per file options and per function options.

https://gcc.gnu.org/wiki/FunctionSpecificOpt
