### ISSUE TITLE
Provide a manpage for new raaz utility

### ISSUE THREAD

**Issue by spwhitton** [raaz-crypto/raaz#305]
It would be great to have a proper manpage for the new utility.

**Comment by piyush-kurur** [comment]
Good idea. I guess it would be better to maintain it in this repo. But before we start that I have 
to say that I have never written a man page before :-( 

Currently there is one top level command raaz which has two subcommands random and checksum. 
Would you like to suggest a structure for the man page. I really do not like the Openssl style pages where each subcommand has a page. It is very difficult to locate the correct man page.

**Comment by spwhitton** [comment]
Dear Piyush,

On Wed, Mar 01, 2017 at 10:44:09AM -0800, Piyush P Kurur wrote:
> Good idea. I guess it would be better to maintain it in this repo. But before
> we start that I have
> to say that I have never written a man page before :-(

Thank you for your interest!

I like perl's POD format for writing manpages.  Alternatives are
asciidoctor and rst2man.

> Currently there is one top level command raaz which has two
> subcommands random and checksum.  Would you like to suggest a
> structure for the man page. I really do not like the Openssl style
> pages where each subcommand has a page. It is very difficult to locate
> the correct man page.

- SYNOPSIS

- DESCRIPTION

- COMMANDS

- OPTIONS

For example: https://manpages.debian.org/testing/dh-make-elpa/dh-make-elpa.1.en.html

-- 
Sean Whitton

**Comment by piyush-kurur** [comment]
If we maintain the man page here on github, then reST is compelling as I think github itself can
render it. So I think rst2man might be the best option. I will mark this for the next release. Meanwhile
if you have a skeleton version can you send me a pull request. I will then see what can be done

**Comment by spwhitton** [comment]
On Thu, Mar 02, 2017 at 01:46:04AM -0800, Piyush P Kurur wrote:
> Meanwhile if you have a skeleton version can you send me a pull
> request. I will then see what can be done

Unfortunately, I don't have a skeleton -- the output from help2man was
too poor to be worth including.

-- 
Sean Whitton

**Comment by piyush-kurur** [comment]
@spwhitton  I have written a basic man page for the raaz command in markdown (some of the details has changed and the man page is the latest interface). The pull request #326 is essentially it. There is a Makefile which builds the man page. Feel free to add some targest there to install it in the appropriate location in the file system.

**Comment by spwhitton** [comment]
Thank you for this.  I'm looking forward to installing the manpage when I upload the next release of raaz to Debian.
