### ISSUE TITLE
FTBFS on big endian architectures

### ISSUE THREAD

**Issue by spwhitton** [raaz-crypto/raaz#306]
raaz is [failing to build on BE archs](https://buildd.debian.org/status/package.php?p=haskell-raaz&suite=experimental).  This is a regression since 0.0.2.

Errors look like this:

    Raaz/Core/Types/Endian.hs:304:22: error:
        * Couldn't match type `a0 -> IO ()' with `IO ()'
          Expected type: BE Word64 -> IO ()
            Actual type: Ptr a0 -> a0 -> IO ()
        * Probable cause: `poke' is applied to too few arguments
          In the expression: poke
          In an equation for `store': store ptr = poke
          In the instance declaration for `EndianStore (BE Word64)'

**Comment by piyush-kurur** [comment]
I will have a look at this. Should be some minor CPP problem. Thanks for reporting

**Comment by piyush-kurur** [comment]
I think I have fixed it. The current tip show have the fix. I bumped the version so that I can release the update on cabal once you confirm that things are fine.

**Comment by piyush-kurur** [comment]
Also please feel free to reopen this if you find that some thing is still not okey.

**Comment by spwhitton** [comment]
I tried the build on a mips box, and can confirm that the problem is fixed.  Thanks!

**Comment by piyush-kurur** [comment]
@spwhitton thanks. Uploaded latest to hackage.

**Comment by piyush-kurur** [comment]
@spwhitton If you do not mind can you upload raaz-0.1.1 to the experimental branch of debian. I would
like to have a look at the build.

**Comment by spwhitton** [comment]
Already done :)  It was just waiting in the NEW queue.

It built successfully.

-- 
Sean Whitton

**Comment by piyush-kurur** [comment]
Thanks. You are awesome. By the way is there a travis like badge that I can put up in the readme for debian builds?

**Comment by spwhitton** [comment]
On Fri, Mar 03, 2017 at 05:53:34PM -0800, Piyush P Kurur wrote:
> Thanks. You are awesome. By the way is there a travis like badge that I can put
> up in the readme for debian builds?

Not that I'm aware of, sorry!  That would be cool.

-- 
Sean Whitton
