### ISSUE TITLE
Liquid haskell specs for Raaz.Core.Types.Tuple.unsafeFromList

### ISSUE THREAD

**Issue by piyush-kurur** [raaz-crypto/raaz#316]
I would like to ensure that whenever  a list is given to `unsafeFromList` it is of the correct size. 
I would like to give some liquid haskell specs of the form
 
```haskell

{-@ unsafeFromList :: (V. Unbox a, Dimension dim) => { xs : list a | size xs = dim } -> Tuple dim a @-}
 
unsafeFromList :: (V.Unbox a, Dimension dim) => [a] -> Tuple dim a
unsafeFromList xs = blah

```
The main difficulty is to make this work as dim is a singleton type capturing type level Nats. So the 
`size xs = dim` portion is not well formed.  As I understand it, I need to define a measure on dim but this is at the type level and I am not sure if it is even possible.

**Comment by piyush-kurur** [comment]
@ranjitjhala any pointers for this? 

A meta question there is not much activity on the #liquidhaskell channel on github. Is it okey to ask such questions on the liquidhaskell issue tracker ?

**Comment by ranjitjhala** [comment]
@piyush-kurur, I didn't even know about the #liquidhaskell @ free node so I wouldn't recommend using it :) I recommend either 

1. the LH github repo (as an issue) or 
2. the slack channel `liquidhaskell.slack.com`

The former has the benefit of being easily searchable...

As to the question: in general refinements cannot talk about types 
but I *think* @nikivazou implemented a way to refer to type-level 
string literals inside refinements (for the string-matching-monoid work?)

Is that the case? If so, can you point us to some examples?

**Comment by ranjitjhala** [comment]
Dear @piyush-kurur,

(Thanks to @nikivazou!)

See this for an example of how to use type-level literals in the refinements. 

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1497409852_1389.hs

Can you point me to your implementation of `unsafeFromList` ... I don't have much experience
with GHC's type level features, so am wondering what it looks like (without the refinements.)

Thanks!

**Comment by piyush-kurur** [comment]
Thanks for a quick response @ranjitjhala , @nikivazou. The `unsafeFromList` is here

https://github.com/raaz-crypto/raaz/blob/master/Raaz/Core/Types/Tuple.hs#L146-L152

As you can see it checks (at run time) whether the dimension of the tuple is equal to the length of the input list and throws an error if it is not. It is used in some places like 

https://github.com/raaz-crypto/raaz/blob/master/Raaz/Hash/Sha1/Internal.hs#L43-L48 

Currently testing is the solution of avoiding this error (at runtime). I would like to make it compile (i.e. liquid haskell) time

The implementation of the helper function `dimension` is given here.

1. https://github.com/raaz-crypto/raaz/blob/master/Raaz/Core/Types/Tuple.hs#L65-L72
2. https://github.com/raaz-crypto/raaz/blob/master/Raaz/Core/Types/Tuple.hs#L80-86

There are two versions to take care of the old and new way of GHC's type level nats.

**Comment by piyush-kurur** [comment]
@nikivazou.  It looks like the solution that you gave should work for me as well. I will try it out and let you know.

**Comment by ranjitjhala** [comment]
Nice! It _should_ be possible to give

  ```
  {-@ dimension  :: (V.Unbox a, Dimension  dim) => Tuple dim a -> {v:Int |
v == dim} @-}

  {-@ assume L.length :: xs:[a] -> {v:Int | v = len xs} @-}

  unsafeFromList :: (V.Unbox a, Dimension dim) => {xs:[a] |  len xs == dim}
-> Tuple dim a
  ```

  which should let you statically check the call in initialise!

**Comment by piyush-kurur** [comment]
thanks @ranjitjhala I will try this out and keep you posted. I just wanted to say liquid haskell is
really awesome (please convey this the other collaborators) and in many ways the only option for the kind of specs I want to give in Raaz other than of course using a full proof assistant like coq. What I like is the pointer stuff for which writing tests are not really possible (at least I do not know of a way to do that).

**Comment by ranjitjhala** [comment]
Glad you like it, will let the others know.

Please do keep me posted if you run into issues, or if you are able to
successfully use it for things!

**Comment by piyush-kurur** [comment]
@ranjitjhala  I tried your suggestion for `dimension`. The error I got is the following

```
 91 | {-@ dimension :: (V.Unbox a, Dimension dim) => Tuple dim a -> {n: Int | n == dim } @-}
                       ^

 The Liquid type

     forall (dim :: GHC.Types.Nat) a ->
GHC.TypeLits.KnownNat dim =>
(dim, a) -> GHC.Types.Int

 is inconsistent with the Haskell type

     forall (dim :: GHC.Types.Nat) a ->
Raaz.Core.Types.Tuple.Dimension dim =>
Raaz.Core.Types.Tuple.Tuple dim a -> GHC.Types.Int

 defined at /home/ppk/code/git/Raaz/raaz/Raaz/Core/Types/Tuple.hs:72:1-9

Completed 2 action(s).
Test suite failure for package raaz-0.2.0
    liquidspec:  exited with: ExitFailure 2
Logs printed to console


```

It looks as if liquid haskell is unable to see through the type synonym. If you think this is a bug in liquid haskell then I can try to isolate a simple case and file it on the liquidhaskell issue tracker.

**Comment by piyush-kurur** [comment]
Just to add the actual code is on https://github.com/piyush-kurur/raaz/blob/liquidhaskell/Raaz/Core/Types/Tuple.hs#L89-L91

**Comment by ranjitjhala** [comment]
Hmm... that is odd ... your hunch is likely correct but
I wonder why this particular type alias is not getting
unfolded.

My _conjecture_ is that perhaps while LH robustly deals
with aliases for plain types, this particular case is
a "type-class constraint" alias and perhaps LH doesn't
handle it properly.

Can you try to "manually" replace the `Dimension`
in the Haskell signature

https://github.com/piyush-kurur/raaz/blob/liquidhaskell/Raaz/Core/Types/Tuple.hs#L80

with `KnownNat` to see if that works? (That would confirm
the hunch above.)

Thanks!

**Comment by piyush-kurur** [comment]
@ranjitjhala Sorry. It was my mistake. Everything is fine. There were two mistakes that I was making.

1. In the liquid type when I use `Tuple` it was confusing with the pair type `(,)`. I fixed this by giving fully qualified name.
2. A non-intuitive behaviour is that  the type parameters (or in this case DataKind) in the Haskell and Liquid haskell should match. For example

If I give 
```haskell

{-@ dimension :: Dimension dim => Raaz.Core.Types.Tuple.Tuple dim a -> { v : Int | v == dim } @-} 
dimension :: Dimension n => Raaz.Core.Types.Tuple.Tuple n a -> Int
```
This leads to an error as I have used `n` in the Haskell type where as `dim` in the Liquid Type. Changing the `n` to `dim` or vice-versa fixes the problem. I can very well understand why this is unavoidable.

What I am left with as of now is some termination checks. I would like to also assert that the function dimension does not evaluate its argument tuple. How do I do that? There are some recursive calls that LH is not able to see that it terminates:

1. https://github.com/piyush-kurur/raaz/blob/liquidhaskell/Raaz/Core/Types/Tuple.hs#L142-L143
2. https://github.com/piyush-kurur/raaz/blob/liquidhaskell/Raaz/Core/Types/Tuple.hs#L168
3. https://github.com/piyush-kurur/raaz/blob/liquidhaskell/Raaz/Core/Types/Tuple.hs#L175

**Comment by piyush-kurur** [comment]
Okey I managed to fix the termination by some minor rewrite. This essentially solves the current issue.
 Thanks @ranjitjhala. I will be pushing the commits soon after cleanup.

**Comment by ranjitjhala** [comment]
Great! (I was just staring at the code to see what termination errors you
were getting... were they in V.replicate?)

**Comment by piyush-kurur** [comment]
The termination errors were due thing things like 

```haskell
someFunction inp = tup
tup = ..... (dimension tup) ... inp ....

```

These kind of recursions were used so that we can get the length of the result type (we need it for the replicate). The essential trick is to rewrite it as the following

```haskell

someFunction = mkTup undefined
mkTup :: (Dimension dim) -> Tuple dim a -> inp -> Tuple dim a
mkTup uTup inp = .....(dimension uTup) ... inp 

```
There is no recursion here.

**Comment by ranjitjhala** [comment]
Ah, I see!

Btw, you could also "disable" the termination check for the original "tup"
by writing:

{-@ lazy tup @-}

**Comment by piyush-kurur** [comment]
Sorry that I did not give the permalink. Hence it might have lead to confusion when I pushed the new version.

Note to self: Be more careful with links.
