### ISSUE TITLE
32-bit windows build fails on appveyor

### ISSUE THREAD

**Issue by piyush-kurur** [raaz-crypto/raaz#342]
It seems that the 32-bit builds (not 64-bit) on appveyor is failing again citing some segmentation problem). I have not done any significant changes to the code since the last successful build. So not sure what is going wrong?

https://ci.appveyor.com/project/raaz-crypto/raaz/build/job/60bib48b90asji5i

Most likely this is an appveyor issue.

**Comment by piyush-kurur** [comment]
@mistuke any comments

**Comment by piyush-kurur** [comment]
To be precise this is the branch release-0.2.0 due to release soon and its package candidate is available on hackage.

**Comment by Mistuke** [comment]
Hmm you might just be tickling a compiler bug, we have some reports about the 32 bit 8.2.x segfaulting, could have been an issue since 8.0.2.

Do you know when a last successful build occurred so I can see a diff? Also I see you have SSE2 checks, do you have any SSE code? l'll see if I can reproduce it locally

**Comment by piyush-kurur** [comment]
Firstly I do not think that windows build is using 8.2.x because the build uses stack lts-8.6 so that rules it out.
I am not using SSE but am definitely probing for SSE and AVX2 in the code in the hope that a future release would be able to select the right implementation at runtime (See #300 for some background discussion). 

The last successful build seems to be ac5c0edc5b93f4ed8dbab2129a87df5b54b5ddbc, which is the commit that includes running the probing code on appveyor.  There has been only three commits since of which only 41e1e902a4202944bc732d88a085d61b5a2bd59c adds anything significant. For all you know this could be
a problem on 32-bit as blake2b uses uint64_t and the way the code is there is some implicit conversions.

 Rest are just documentation stuff.

**Comment by Mistuke** [comment]
Right, so had some time to take a look, it is 41e1e90 that's causing the trouble. You changed `int` to `uint64_t` but left the Haskell bindings to the C code as `Int`. However the Haskell report only specifies that `Int` has at least `29 bits`.  Int is tied to the platform `int` so on 32-bit it'll be 32 bit. This is causing the stack frame to get messed up and the `PC` ending at a weird location in non-executable region, hence the segfault.

Also the type of `raazHashBlake2bPortableLastBlock` is suspicious as it imports `Pointer` as it's first argument while the C code isn't one.

**Comment by piyush-kurur** [comment]
I will have a look at this. Meanwhile let me see how does the debian builds on 32 archs fair.

**Comment by piyush-kurur** [comment]
@mistuke I think you were correct about the type mismatch. I just fixed the bug in 9f515cc576ba8e7d7e9778228315301ff698554e
