### ISSUE TITLE
Fix appveyor to build against 32-bit windows as well

### ISSUE THREAD

**Issue by piyush-kurur** [raaz-crypto/raaz#360]
@Mistuke I opened this ticket just to remind myself of fixing this issue.

**Comment by piyush-kurur** [comment]
Because I am not too familiar with the windows environment, and do not have a windows machine either, can you tell me what exactly needs to be done to ensure a 32-bit environment.

Quoted below is the part of the appveyor.yml that I think is most relevant.

```
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
- choco install -y ghc --version %GHCVER%
- refreshenv
```

I will I guess need to change mingw64 to something mingw32 (is that correct). Also how do I pick the appropriate version in choco.

**Comment by Mistuke** [comment]
No the host tools don't matter. Ghc is completely self contained. The only thing you have to do is when you want the 32 bit ghc to pass `-x86`  to the `choco install` command.
