### ISSUE TITLE
Gadget and Refactored Memory and SecureMemory

### ISSUE THREAD

**Issue by satvikc** [raaz-crypto/raaz#54]
I have added the gadget class and refactored memory and SecureMemory.

* I have moved from Using the state monad to just a function which takes `BookKeeper` as the argument. It was not possible to compose memory instances if we were using state monad.

* Also I have moved from `mmap` to `posix_memalign` and wrote tests to detect if it is available. The code is portable in the sense that it sets and checks necessary flags.

* `MAC` and `Hash` are broken because of the new gadget interface. 

Here is the link https://github.com/satvikc/raaz/tree/x-memory/raaz-primitives/Raaz

**Comment by piyush-kurur** [comment]
The interface is no more relevant I am closing this issue
