### ISSUE TITLE
Exporting default parser and write 

### ISSUE THREAD

**Issue by satvikc** [raaz-crypto/raaz#90]
Since parse and write for basic datatypes like `Word8`, `Word32` etc. are used in lots of places and its repetitive to mention them in all the places we should export these specialized functions from raaz-primitives. Something like

``` haskell
parseByte :: Parser Word8
parseByte = parse

writeByte :: Word8 -> Write
writeByte = write

parseWord32 :: Parser Word32
parseWord32 = parse
.
.
.
```

**Comment by piyush-kurur** [comment]
Not relevant anymore
